apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: your_docker_registry/notification-service:latest
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: '3000'
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: secret
            - name: MONGO_URI
              value: 'mongodb://mongo-service:27017/notification_service'
            - name: REDIS_HOST
              value: 'redis-service'
            - name: REDIS_PORT
              value: '6379'
            - name: RABBITMQ_URL
              value: 'amqp://rabbitmq-service'
            - name: RABBITMQ_QUEUE
              value: 'notification_queue'
