version: '3.8'

services:
  notification-service:
    build: .
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - JWT_SECRET=your_jwt_secret
      - MONGO_URI=mongodb://mongo:27017/notification_service
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_URL=amqp://rabbitmq
      - RABBITMQ_QUEUE=notification_queue
    depends_on:
      - mongo
      - redis
      - rabbitmq

  mongo:
    image: mongo:4.4
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:6
    ports:
      - '6379:6379'

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

volumes:
  mongo_data:
