apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-security-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-security-service
  template:
    metadata:
      labels:
        app: auth-security-service
    spec:
      containers:
        - name: auth-security-service
          image: your_docker_registry/auth-security-service:latest
          ports:
            - containerPort: 8443
          env:
            - name: DB_HOST
              value: "db-service"
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: secret
          volumeMounts:
            - name: tls-certs
              mountPath: "/app/certs"
      volumes:
        - name: tls-certs
          secret:
            secretName: tls-secret
