version: '3.8'

services:
  auth-security-service:
    build: .
    ports:
      - '8443:8443'
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=your_db_password
      - DB_NAME=auth_db
      - JWT_SECRET_KEY=your_jwt_secret_key
    volumes:
      - ./certs:/app/certs
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: auth_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
