version: '3.8'

services:
  data-management-service:
    build: .
    ports:
      - '8082:8082'
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - JWT_SECRET=your_jwt_secret
      - ETHEREUM_ENDPOINT=https://ropsten.infura.io/v3/YOUR_INFURA_PROJECT_ID
      - CONTRACT_ADDRESS=0xYourContractAddress
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5.0
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
