apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-analytics-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ai-analytics-service
  template:
    metadata:
      labels:
        app: ai-analytics-service
    spec:
      containers:
        - name: ai-analytics-service
          image: your_docker_registry/ai-analytics-service:latest
          ports:
            - containerPort: 8000
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"
            - name: REDIS_HOST
              value: "redis-service"
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: secret
