openapi: 3.0.0
info:
  title: API Gateway
  version: 1.0.0
paths:
  /api/v1/users:
    get:
      summary: Get Users
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
