serverAddress: ":8443"
tlsCertFile: "certs/server.crt"
tlsKeyFile: "certs/server.key"
database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "your_db_password"
  name: "auth_db"
  sslMode: "disable"
jwtSecretKey: "your_jwt_secret_key"
