version: '3.8'

services:
  identity-service:
    build: .
    ports:
      - '8080:8080'
    environment:
      - DATABASE_URL=postgres://user:password@postgres:5432/identity_service?sslmode=disable
      - JWT_SECRET=your_secret_key
    depends_on:
      - postgres

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: identity_service
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
