version: '3.8'

services:
  integration-service:
    build: .
    ports:
      - '4000:4000'
    environment:
      - PORT=4000
      - JWT_SECRET=your_jwt_secret
      - MONGO_URI=mongodb://mongo:27017/integration_service
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:4.4
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:6
    ports:
      - '6379:6379'

volumes:
  mongo_data:
